name: Deploy PHP on AWS EC2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOSTNAME  }}
          REMOTE_USER: ${{ secrets.USER_NAME  }}
          TARGET: /usr/share/nginx/html/aws-ec2-php