name: SSH without Actions

# on: [push, workflow_dispatch]
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    env:
          SSH_USER: ${{ secrets.USER_NAME }}
          SSH_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOSTNAME }}

    steps:
      # - name: Configure SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_KEY" > ~/.ssh/staging.key
      #     chmod 600 ~/.ssh/staging.key
      #     cat >>~/.ssh/config <<END
      #     Host staging
      #       HostName $SSH_HOST
      #       User $SSH_USER
      #       IdentityFile ~/.ssh/staging.key
      #       StrictHostKeyChecking no
      #     END
    
      - name: Run SSH Commands
        uses: malikabid/manualssh@main
        with:
          host: $SSH_HOST
          username: $SSH_USER
          key: $SSH_KEY
          script: |
           cd /usr/share/nginx/html/ 
           git checkout main && git pull

      # - name: Check the current User
      #   run: ssh staging 'whoami'

      # - name: Pull files from repo
      #   run: ssh staging 'cd /usr/share/nginx/html/ && git checkout main && git pull'


